name: Deploy
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: Set-up GitHub
        uses: actions/checkout@v2

      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env

      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install

      - name: Deploy
        run: PYTHONPATH=src/ poetry run python -m mkdocs gh-deploy --force